CREATE TABLE users (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(255) NOT NULL,
    email           varchar(512) NOT NULL,
    CONSTRAINT  UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE requests (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     varchar(200) NOT NULL,
    requester_id    integer REFERENCES users (id)
);

CREATE TABLE items (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(64) NOT NULL,
    description     varchar(200) NOT NULL,
    is_available    boolean NOT NULL,
    owner_id        integer REFERENCES users (id),
    request_id      integer REFERENCES requests (id)
);

CREATE TABLE comments (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text            varchar(500) NOT NULL,
    item_id         integer REFERENCES items (id),
    author_id       integer REFERENCES users (id),
    created         timestamp NOT NULL
);

CREATE TABLE bookings (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date      timestamp,
    end_date        timestamp,
    item_id         integer REFERENCES items (id),
    booker_id       integer REFERENCES users (id),
    status          varchar(32)
);